version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Password123"
      MSSQL_PID: "Developer"
    volumes:
      - db_data:/var/opt/mssql
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "YourStrong!Password123", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;databaseName=blogdb;encrypt=true;trustServerCertificate=true
      JWT_SECRET: your-512-bit-secret-key-here-1234567890ABCDEF
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_data: